### ISSUE TITLE
Unable to get to http://deep-shading-datasets.mpi-inf.mpg.de/

### ISSUE THREAD

**Issue by rharihara11** [marcelsan/DeepShading#7]
unable to get to http://deep-shading-datasets.mpi-inf.mpg.de/ to download the datasets.. Can you please check?

**Comment by marcelsan** [comment]
Hi, 

Thanks for pointing that out. Unfortunately, I will not be able to address this specific issue because I do not maintain the website of the paper. This repository is just an unofficial implementation of the paper and any question related to the dataset should be forwarded to the authors of the paper. I recommend you to contact directly to them.

Thanks!
